Update readme with quickstart steps
Aiven-Open/opensearch-connector-for-apache-kafka pull request #283
Opened 2024-05-18 12:25 UTC by muralibasani

This PR updates the below.

- There is a worker properties file which is still in the name of elasticsearch. Renamed to opensearch
- Updated readme file with quickstart steps
- As this connector is a sink connector, updated the heading.

2024-05-21 08:33 UTC, Claudenw requested changes
I think the structure should be front to back.  I should not have to stop and install new stuff part way through.  All the required components should be listed at the beginning.

2024-05-21 08:33 UTC, Claudenw commented on README.md
> +6. Install and Run OpenSearch: Ensure OpenSearch is installed and running. If SSL is enabled, configure the credentials in the connector worker properties.
Shouldn't this come at the beginning?  It seems like you should have a single first step:

1. Install and configure required software:
    1. Install and Run Kafka (link to install notes)
    2. Install and Run Kafka Connect (link to install notes)
    3. Install and Run OpenSearch (link to install notes) Mention SSL issue

2024-05-21 09:07 UTC, muralibasani commented on README.md
> +6. Install and Run OpenSearch: Ensure OpenSearch is installed and running. If SSL is enabled, configure the credentials in the connector worker properties.
@Claudenw good one. Updated.

2024-05-21 09:07 UTC, muralibasani commented on README.md
> +5. Check ACLs (If Enabled): If ACLs are enabled on Kafka, ensure there are no authorization exceptions for the topic and group resources.
Updated with links.

2024-05-21 13:52 UTC, Claudenw requested changes

2024-05-21 13:52 UTC, Claudenw commented on README.md
> +3. Add OpenSearch Sink to Kafka Connect: Follow the 'How to install' instructions to add the OpenSearch sink connector to Kafka Connect. Example worker config is located here https://github.com/Aiven
I think you can replace 1. and 2. in this list with "Ensure that the required software is installed and running"
You can then also drop 6 and 7 from this list as it is covered in the required software..

2024-05-21 14:45 UTC, muralibasani commented on README.md
> +3. Add OpenSearch Sink to Kafka Connect: Follow the 'How to install' instructions to add the OpenSearch sink connector to Kafka Connect. Example worker config is located here https://github.com/Aiven
ah yes. done.

2024-05-24 13:38 UTC, Claudenw approved these changes
LGTM -- thx for the changes.

2024-05-24 13:41 UTC, merged